import { ServiceCategory } from './types';

export interface CategoryCardDef {
  id: ServiceCategory;
  name: string;
  subtitle: string;
  iconName: 'wrench' | 'zap' | 'car' | 'gear' | 'tire' | 'snowflake' | 'bottle' | 'plus';
  iconColor: string;
  bgLight: string;
}

export const CATEGORY_CARDS: CategoryCardDef[] = [
  {
    id: 'mehanika',
    name: 'Mehanika',
    subtitle: 'Općenito održavanje',
    iconName: 'wrench',
    iconColor: '#1D68F2',
    bgLight: 'bg-blue-50/70',
  },
  {
    id: 'elektrika',
    name: 'Elektrika',
    subtitle: 'Električni sistem',
    iconName: 'zap',
    iconColor: '#EA580C',
    bgLight: 'bg-amber-50/70',
  },
  {
    id: 'limarija',
    name: 'Limarija',
    subtitle: 'Karoserija i lim',
    iconName: 'car',
    iconColor: '#EF4444',
    bgLight: 'bg-red-50/70',
  },
  {
    id: 'oprema',
    name: 'Oprema',
    subtitle: 'Dodatna oprema',
    iconName: 'gear',
    iconColor: '#9333EA',
    bgLight: 'bg-purple-50/70',
  },
  {
    id: 'gume_felge',
    name: 'Gume i felge',
    subtitle: 'Gume, felge, balansiranje',
    iconName: 'tire',
    iconColor: '#1E293B',
    bgLight: 'bg-slate-100/70',
  },
  {
    id: 'klima',
    name: 'Klima uređaj',
    subtitle: 'Klima i grijanje',
    iconName: 'snowflake',
    iconColor: '#0284C7',
    bgLight: 'bg-sky-50/70',
  },
  {
    id: 'tekucine',
    name: 'Tekućine',
    subtitle: 'Ulja, antifriz, tekućine',
    iconName: 'bottle',
    iconColor: '#2563EB',
    bgLight: 'bg-blue-50/70',
  },
  {
    id: 'ostalo',
    name: 'Ostalo',
    subtitle: 'Ostali radovi',
    iconName: 'plus',
    iconColor: '#475569',
    bgLight: 'bg-slate-100/70',
  },
];

export interface WorkGroup {
  name: string;
  items: string[];
}

export const SERVICE_CATALOG: Partial<Record<ServiceCategory, WorkGroup[]>> = {
  mehanika: [
    {
      name: 'MOTOR',
      items: [
        'Motorno ulje',
        'Filter ulja',
        'Filter zraka',
        'Filter goriva',
        'Filter kabine',
        'Svjećice',
        'Grijači',
        'Zračni filter',
        'PCV ventil',
        'EGR ventil',
        'Čišćenje EGR ventila',
        'Čišćenje usisa',
        'MAF senzor',
        'MAP senzor',
        'Lambda sonda',
        'Termostat',
        'Vodena pumpa',
        'PK remen',
        'Natezač PK remena',
        'Zatezač',
        'Zupčasti remen',
        'Set zupčastog remena',
        'Lanac razvoda',
        'Natezač lanca',
        'Klizači lanca',
        'Brtve motora',
        'Poklopac ventila',
        'Karter',
        'Radilica',
        'Bregasta osovina',
        'Turbo punjač',
        'Intercooler',
        'Crijeva turbine',
        'Ostalo – motor',
      ],
    },
    {
      name: 'KVAČILO I MJENJAČ',
      items: [
        'Set kvačila',
        'Kvačilo',
        'Zamajac',
        'Dvomaseni zamajac',
        'Potisni ležaj',
        'Hidraulika kvačila',
        'Sajla kvačila',
        'Ulje mjenjača',
        'Filter mjenjača',
        'Brtva mjenjača',
        'Servis automatskog mjenjača',
        'Ispiranje automatskog mjenjača',
        'Mehatronika',
        'Ostalo – mjenjač i kvačilo',
      ],
    },
    {
      name: 'POGON',
      items: [
        'Diferencijal',
        'Ulje diferencijala',
        'Prednji diferencijal',
        'Zadnji diferencijal',
        'Reduktor',
        'Ulje reduktora',
        'Razvodna kutija',
        'Ulje razvodne kutije',
        'Kardansko vratilo',
        'Kardan',
        'Haldex',
        'Haldex ulje',
        'Haldex filter',
        'Servis Haldexa',
        'Poluosovina',
        'Homokinetički zglob',
        'Manžetna poluosovine',
        'Ostalo – pogon',
      ],
    },
    {
      name: 'OVJES I UPRAVLJANJE',
      items: [
        'Amortizeri',
        'Prednji amortizeri',
        'Zadnji amortizeri',
        'Opruge',
        'Prednje opruge',
        'Zadnje opruge',
        'Kugle',
        'Krajnice',
        'Sponice',
        'Stabilizatori',
        'Gumice stabilizatora',
        'Vilice',
        'Selene',
        'Ležajevi amortizera',
        'Ležaj točka',
        'Glavčina točka',
        'Letva volana',
        'Servo pumpa',
        'Servo tekućina',
        'Geometrija trapa',
        'Centriranje trapa',
        'Ostalo – ovjes i upravljanje',
      ],
    },
    {
      name: 'KOČNICE',
      items: [
        'Prednje kočione pločice',
        'Zadnje kočione pločice',
        'Prednji diskovi',
        'Zadnji diskovi',
        'Kočione čeljusti',
        'Reparacija kočionih čeljusti',
        'Kočiona crijeva',
        'Kočione cijevi',
        'Kočiona tekućina',
        'Odzračivanje kočnica',
        'Ručna kočnica',
        'Električna ručna kočnica',
        'ABS senzor',
        'ABS sistem',
        'Ostalo – kočnice',
      ],
    },
    {
      name: 'HLAĐENJE MOTORA',
      items: [
        'Rashladna tekućina / antifriz',
        'Ispiranje sistema hlađenja',
        'Termostat',
        'Vodena pumpa',
        'Hladnjak',
        'Ventilator hladnjaka',
        'Crijevo rashladnog sistema',
        'Ekspanziona posuda',
        'Čep ekspanzione posude',
        'Ostalo – hlađenje',
      ],
    },
    {
      name: 'ISPUŠNI SISTEM',
      items: [
        'Auspuh',
        'DPF filter',
        'Čišćenje DPF-a',
        'EGR',
        'Katalizator',
        'Lambda sonda',
        'FAP',
        'AdBlue sistem',
        'AdBlue tekućina',
        'Senzor pritiska',
        'Fleksibilna cijev',
        'Ostalo – ispuh',
      ],
    },
    {
      name: 'REMENJE I LANAC',
      items: [
        'Zupčasti remen',
        'Set zupčastog remena',
        'PK remen',
        'Natezač PK remena',
        'Zatezač',
        'Lanac razvoda',
        'Set lanca razvoda',
        'Klizači lanca',
        'Ostalo – remenje i lanac',
      ],
    },
  ],

  tekucine: [
    {
      name: 'MOTORNA ULJA',
      items: ['Motorno ulje'],
    },
    {
      name: 'MJENJAČ',
      items: ['Ulje ručnog mjenjača', 'Ulje automatskog mjenjača', 'Servis automatskog mjenjača'],
    },
    {
      name: 'POGON',
      items: ['Ulje diferencijala', 'Ulje reduktora', 'Haldex ulje', 'Ulje razvodne kutije'],
    },
    {
      name: 'KOČNICE',
      items: ['Kočiona tekućina'],
    },
    {
      name: 'HLAĐENJE',
      items: ['Antifriz / rashladna tekućina'],
    },
    {
      name: 'UPRAVLJANJE',
      items: ['Servo tekućina'],
    },
    {
      name: 'OSTALO',
      items: ['AdBlue', 'Tekućina za stakla', 'Ostalo'],
    },
  ],

  elektrika: [
    {
      name: 'AKUMULATOR I PUNJENJE',
      items: [
        'Akumulator',
        'Zamjena akumulatora',
        'Test akumulatora',
        'Alternator',
        'Reparacija alternatora',
        'Anlaser',
        'Reparacija anlasera',
      ],
    },
    {
      name: 'RASVJETA',
      items: [
        'Prednja sijalica',
        'Zadnja sijalica',
        'Stop svjetlo',
        'Žmigavac',
        'Pozicijsko svjetlo',
        'Maglenka',
        'LED svjetlo',
        'Xenon',
        'Far',
        'Stražnje svjetlo',
      ],
    },
    {
      name: 'ELEKTRONIKA',
      items: [
        'Dijagnostika',
        'ECU',
        'Senzor',
        'Parking senzori',
        'Kamera',
        'Centralno zaključavanje',
        'Električni podizači',
        'Električni retrovizori',
        'Ostalo – elektrika',
      ],
    },
  ],

  limarija: [
    {
      name: 'KAROSERIJA, LIM I STAKLA',
      items: [
        'Popravka lima',
        'Lakiranje',
        'Poliranje',
        'Ogrebotina',
        'Udubljenje',
        'Branik',
        'Hauba',
        'Vrata',
        'Blatobran',
        'Prag',
        'Krov',
        'Gepek',
        'Vjetrobransko staklo',
        'Bočno staklo',
        'Zadnje staklo',
        'Zamjena stakla',
        'Antikorozivna zaštita',
        'Ostalo – limarija',
      ],
    },
  ],

  gume_felge: [
    {
      name: 'GUME, FELGE I VULKANIZACIJA',
      items: [
        'Kupovina guma',
        'Zamjena guma',
        'Montaža guma',
        'Demontaža guma',
        'Balansiranje',
        'Krpljenje gume',
        'Vulkanizerski rad',
        'Geometrija',
        'Centriranje trapa',
        'Kupovina felgi',
        'Zamjena felgi',
        'Popravka felge',
        'Sezonska zamjena (Ljetne → Zimske)',
        'Sezonska zamjena (Zimske → Ljetne)',
        'Skladištenje guma',
        'Ostalo – gume/felge',
      ],
    },
  ],

  klima: [
    {
      name: 'KLIMA I GRIJANJE',
      items: [
        'Servis klime',
        'Punjenje klime',
        'Plin klime',
        'Kompresor klime',
        'Filter kabine',
        'Dezinfekcija klime',
        'Čišćenje klime',
        'Ventilator kabine',
        'Grijanje',
        'Ostalo – klima',
      ],
    },
  ],

  oprema: [
    {
      name: 'DODATNA OPREMA',
      items: [
        'Multimedija',
        'Radio',
        'Zvučnici',
        'Kamera',
        'Parking senzori',
        'Dash kamera',
        'GPS',
        'Krovni nosači',
        'Krovna kutija',
        'Felge',
        'Presvlake',
        'Patosnice',
        'LED rasvjeta',
        'Xenon',
        'Alu felge',
        'Zatamnjivanje stakala',
        'Folije',
        'Webasto',
        'Grijanje sjedišta',
        'Ostalo',
      ],
    },
  ],

  ostalo: [
    {
      name: 'OSTALI RADOVI I USLUGE',
      items: [
        'Pranje i čišćenje vozila',
        'Dubinsko čišćenje',
        'Tehnički pregled',
        'Registracija vozila',
        'Osiguranje',
        'Ostali radovi',
      ],
    },
  ],
};
